#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sum:
  path: /sum/{a}/{b}
  controller: App\Controller\SumController::sumAction

positions:
  path: /positions/{id}
  controller: App\Controller\PositionController::positionsAction